---
apiVersion: v1beta1
kind: Kustomization

namespace: theatre-system
namePrefix: theatre-

commonLabels:
  app: theatre

resources:
  - ../crds/rbac_v1alpha1_directoryrolebindings.yaml
  - ../crds/workloads_v1alpha1_consoles.yaml
  - ../managers/rbac.yaml

secretGenerator:
  - commands:
      # Assuming the current GOOGLE_APPLICATION_CREDENTIALS env var points at
      # the key we want to use during deployment.
      credentials.json: cat $GOOGLE_APPLICATION_CREDENTIALS
    name: google-application-credentials
