required = [
  "k8s.io/code-generator/cmd/client-gen"
]

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.3"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    go-tests = false

  [[prune.project]]
    name = "k8s.io/gengo"
    unused-packages = false
    go-tests = false
