required = [
  "github.com/onsi/ginkgo",
  "github.com/onsi/gomega",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
]

[[override]]
  name="k8s.io/code-generator"
  version="kubernetes-1.12.4"

[[constraint]]
  name="sigs.k8s.io/controller-runtime"
  version="v0.1.1"

[[constraint]]
  name="sigs.k8s.io/controller-tools"
  version="v0.1.1"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.3"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    go-tests = false

  [[prune.project]]
    name = "k8s.io/gengo"
    unused-packages = false
    go-tests = false
