required = [
  "github.com/onsi/ginkgo",
  "github.com/onsi/gomega",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "sigs.k8s.io/controller-tools/cmd/controller-gen",
]

[[constraint]]
  name="sigs.k8s.io/controller-runtime"
  version="v0.1.10"

[[constraint]]
  name = "sigs.k8s.io/controller-tools"
  version = "v0.1.9"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"

[[constraint]]
  name ="k8s.io/kubernetes"
  version = "v1.13.1"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.3"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    go-tests = false

  [[prune.project]]
    name = "k8s.io/gengo"
    unused-packages = false
    go-tests = false

[[constraint]]
  name = "gopkg.in/h2non/gock.v1"
  version = "1.0.12"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "1.2.4"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.1"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "v1.5.2"