---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sudorolebindings.rbac.lawrjone.xyz
spec:
  group: rbac.lawrjone.xyz
  names:
    plural: sudorolebindings
    singular: sudorolebinding
    kind: SudoRoleBinding
    shortNames:
      - srb
      - srbs
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: >
            APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the
            latest internal value, and may reject unrecognized values.
          type: string
        kind:
          description: >
            Kind is a string value representing the REST resource this object
            represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase.
          type: string
        metadata:
          type: object
        spec:
          properties:
            roleBinding:
              properties:
                roleRef:
                  properties:
                    apiGroup:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
        status:
          properties:
            grants:
              type: array
              items:
                properties:
                  subject:
                    type: object
                  expiry:
                    type: string
