---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: directoryrolebindings.rbac.lawrjone.xyz
spec:
  group: rbac.lawrjone.xyz
  names:
    plural: directoryrolebindings
    singular: directoryrolebinding
    kind: DirectoryRoleBinding
    shortNames:
      - drb
      - drbs
  version: v1alpha1
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: >
            APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the
            latest internal value, and may reject unrecognized values.
          type: string
        kind:
          description: >
            Kind is a string value representing the REST resource this object
            represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase.
          type: string
        metadata:
          type: object
        roleRef:
          type: object
        subjects:
          type: array
