apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: consoletemplates.workloads.crd.gocardless.com
spec:
  group: workloads.crd.gocardless.com
  names:
    kind: ConsoleTemplate
    plural: consoletemplates
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description:
            "APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources"
          type: string
        kind:
          description:
            "Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds"
          type: string
        metadata:
          type: object
        spec:
          properties:
            additionalAttachSubjects:
              items:
                type: object
              type: array
            authorisationRules:
              description:
                List of authorisation rules to match against in order from
                top to bottom.
              items:
                properties:
                  authorisationsRequired:
                    description:
                      The number of authorisations required from members
                      of the subjects before the console can run.
                    format: int64
                    type: integer
                  matchCommandElements:
                    description:
                      "The matching rule to compare to the command and
                      arguments of the console.  This uses basic wildcard matching:
                      Each element of the array is evaluated against the corresponding
                      element of the console's `spec.command` field. An element consisting
                      of a single `*` character will assert on the presence of an
                      element, but will allow any contents. An element consisting
                      of `**`, at the end of the match array, will match 0 or more
                      additional elements in the command, but can only be used at
                      the end of the rule.  Pattern matching _within_ elements is
                      deliberately not supported, as this makes it much harder to
                      construct rules which are secure and do not allow chaining of
                      additional commands (e.g. in a shell context)."
                    items:
                      type: string
                    minItems: 1
                    type: array
                  name:
                    description:
                      Human readable name of authorisation rule added to
                      logs for auditing.
                    type: string
                  subjects:
                    description:
                      List of subjects that can provide authorisation for
                      the console command to run.
                    items:
                      type: object
                    type: array
                required:
                  - name
                  - matchCommandElements
                  - authorisationsRequired
                  - subjects
                type: object
              type: array
            defaultAuthorisationRule:
              description:
                Default authorisation rule to use if no authorisation rules
                are defined or no authorisation rules match.
              properties:
                authorisationsRequired:
                  description:
                    The number of authorisations required from members
                    of the subjects before the console can run.
                  format: int64
                  type: integer
                subjects:
                  description:
                    List of subjects that can provide authorisation for
                    the console command to run.
                  items:
                    type: object
                  type: array
              required:
                - authorisationsRequired
                - subjects
              type: object
            defaultTimeoutSeconds:
              description:
                Default time, in seconds, that a Console will be created
                for. Maximum value of 1 week (as per MaxTimeoutSeconds).
              format: int64
              maximum: 604800
              minimum: 0
              type: integer
            defaultTtlSecondsAfterFinished:
              description:
                Specifies the TTL for any Console created with this template.
                If set, the Console will be eligible for garbage collection DefaultTTLSecondsAfterFinished
                seconds after it enters the Stopped or Destroyed phase. If not set,
                this value defaults to 24 hours. This field is modeled closely on
                the TTL mechanism in Kubernetes 1.12.
              format: int32
              maximum: 604800
              minimum: 0
              type: integer
            maxTimeoutSeconds:
              description:
                Maximum time, in seconds, that a Console can be created
                for. Maximum value of 1 week.
              format: int64
              maximum: 604800
              minimum: 0
              type: integer
            template:
              type: object
            ttlSecondsBeforeRunning:
              description:
                Specifies the TTL before running for any Console created
                with this template. If set, the Console will be eligible for garbage
                collection TTLSecondsBeforeRunning seconds if it has not progressed
                to the Running phase. If not set, this value defaults to 60 minutes.
                This field is modeled on the TTL mechanism in Kubernetes 1.12.
              format: int32
              maximum: 86400
              minimum: 0
              type: integer
          required:
            - template
            - defaultTimeoutSeconds
            - maxTimeoutSeconds
          type: object
      required:
        - spec
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
