---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: release-validate
  annotations:
    cert-manager.io/inject-ca-from: theatre-system/theatre-release-manager
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: Cg==
      service:
        name: theatre-release-manager
        namespace: theatre-system
        path: /validate-releases
        port: 443
    failurePolicy: Fail
    name: release.deploy.crd.gocardless.com
    rules:
      - apiGroups:
          - deploy.crd.gocardless.com
        apiVersions:
          - v1alpha1
        operations:
          - UPDATE
        resources:
          - releases
        scope: "*"
    sideEffects: None
    timeoutSeconds: 10
