---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: releases.deploy.gocardless.com
spec:
  group: deploy.gocardless.com
  names:
    kind: Release
    listKind: ReleaseList
    plural: releases
    singular: release
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          config:
            description: ReleaseConfig the release configuration
            properties:
              revisions:
                description: |-
                  Revisions is a list of revisions to be released. Each revision.name must be
                  unique across all revisions
                items:
                  properties:
                    id:
                      description: ID is the unique identifier of the revision (e.g.,
                        commit SHA, image digest, chart version)
                      type: string
                    metadata:
                      description: Metadata contains additional optional information
                        about the revision
                      properties:
                        author:
                          description: Author is the author of the commit, if available.
                            The field is optional.
                          type: string
                        branch:
                          description: Branch is the branch of the commit, if available.
                            The field is optional.
                          type: string
                        message:
                          description: Message is the message of the commit, if available.
                            The field is optional.
                          type: string
                      type: object
                    name:
                      description: Name is unique identifier for this revision. E.g.
                        application-revision, chart-revision, etc.
                      type: string
                    source:
                      description: Source identifies where this revision comes from
                        (e.g., repository URL, registry URL)
                      type: string
                    type:
                      description: Type specifies the kind of revision source (git,
                        container_image, helm_chart)
                      type: string
                  required:
                  - id
                  - name
                  type: object
                maxItems: 10
                minItems: 1
                type: array
              targetName:
                description: TargetName is a namespace-unique identifier for this
                  release target
                type: string
            required:
            - revisions
            - targetName
            type: object
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          status:
            description: Status defines the observed state of Release
            properties:
              conditions:
                description: |-
                  Conditions represent the latest available observations of a release's state.
                  Known conditions are:
                  * Active
                  * Healthy
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              deploymentEndTime:
                description: DeploymentEndTime is the time when the release was completed.
                format: date-time
                type: string
              deploymentStartTime:
                description: DeploymentStartTime is the time when the release was
                  started.
                format: date-time
                type: string
              message:
                description: Message is a human-readable message indicating the state
                  of the release.
                type: string
              nextRelease:
                description: NextRelease is the name of the release that superseded
                  this release.
                properties:
                  releaseRef:
                    description: Release which superseded this release
                    type: string
                  transitionTime:
                    description: When the release transitioned to this state
                    format: date-time
                    type: string
                type: object
              observedGeneration:
                description: The generation observed by the release controller.
                format: int64
                type: integer
              previousRelease:
                description: PreviousRelease is the name of the release that was superseded
                  by this release.
                properties:
                  releaseRef:
                    description: Release which superseded this release
                    type: string
                  transitionTime:
                    description: When the release transitioned to this state
                    format: date-time
                    type: string
                type: object
              signature:
                description: |-
                  Signature is deterministic hash constructed out of the release revisions.
                  The signature is constructed out of the sum of names and ids of each revision.
                type: string
            type: object
        required:
        - config
        type: object
    served: true
    storage: true
    subresources:
      status: {}
